config/routes.rb
Crypsis::Application.routes.draw do
  

  match'/newcol', :to =>'columns#new'

  resources :columns do
    resources :rows
  end  

  resources :tables

  root :to => 'tables#index'

end

app/models/column.rb
class Column < ActiveRecord::Base
  attr_accessible :data1, :data2, :data3, :data4, :table_id
  belongs_to :table
  has_many :rows ,:dependent => :destroy
end

app/models/row.rb
class Row < ActiveRecord::Base
  attr_accessible :column_id, :value1, :value2, :value3, :value4
  belongs_to :column
end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :description, :name, :parent_id
  has_many :tables ,:dependent => :destroy
  has_one :column ,  :dependent=> :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  # GET /columns
  # GET /columns.json
  def index
    @columns = Column.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @columns }
    end
  end

  # GET /columns/1
  # GET /columns/1.json
  def show
    @column = Column.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @column }
    end
  end

  # GET /columns/new
  # GET /columns/new.json
  def new
    @column = Column.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @column }
    end
  end

  # GET /columns/1/edit
  def edit
    @column = Column.find(params[:id])
  end

  # POST /columns
  # POST /columns.json
  def create
    @column = Column.new(params[:column])

    respond_to do |format|
      if @column.save
        format.html { redirect_to @column, notice: 'Column was successfully created.' }
        format.json { render json: @column, status: :created, location: @column }
      else
        format.html { render action: "new" }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /columns/1
  # PUT /columns/1.json
  def update
    @column = Column.find(params[:id])

    respond_to do |format|
      if @column.update_attributes(params[:column])
        format.html { redirect_to @column, notice: 'Column was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /columns/1
  # DELETE /columns/1.json
  def destroy
    @column = Column.find(params[:id])
    @column.destroy

    respond_to do |format|
      format.html { redirect_to columns_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  # GET /rows
  # GET /rows.json
  before_filter :get_column
  def index
    #@rows = Row.all
    @rows=@column.rows

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rows }
    end
  end

  # GET /rows/1
  # GET /rows/1.json
  def show
   # @row = Row.find(params[:id])
   @row=@column.rows.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @row }
    end
  end

  # GET /rows/new
  # GET /rows/new.json
  def new
    #@row = Row.new
    @column=Column.find(params[:column_id])
    @row=@column.rows.build 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @row }
    end
  end

  # GET /rows/1/edit
  def edit
   # @row = Row.find(params[:id])
   @row=@column.rows.find(params[:id])
  end

  # POST /rows
  # POST /rows.json
  def create
    #@row = Row.new(params[:row])
    @row=@column.rows.build(params[:row])
    respond_to do |format|
      if @row.save
        format.html { redirect_to column_rows_url(@column), notice: 'Row was successfully created.' }
        format.json { render json: @row, status: :created, location: @row }
      else
        format.html { render action: "new" }
        format.json { render json: @row.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rows/1
  # PUT /rows/1.json
  def update
   # @row = Row.find(params[:id])
   @row=@column.rows.find(params[:id])

    respond_to do |format|
      if @row.update_attributes(params[:row])
        format.html { redirect_to column_rows_url(@column), notice: 'Row was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rows/1
  # DELETE /rows/1.json
  def destroy
   # @row = Row.find(params[:id])
   @row=@column.rows.find(params[:id])
    @row.destroy

    respond_to do |format|
      format.html { redirect_to column_rows_path(@column) }
      format.json { head :no_content }
    end
  end
  private
  def get_column
    @column=Column.find(params[:column_id])
  end  
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])
    @col=Column.find_by_table_id(params[:id])
    @par=Table.find_all_by_parent_id(params[:id]) 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/rows_helper.rb
module RowsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/columns/_form.html.erb
<%= form_for(@column) do |f| %>
  <% if @column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
      <% @column.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data1 %><br />
    <%= f.text_field :data1 %>
  </div>
  <div class="field">
    <%= f.label :data2 %><br />
    <%= f.text_field :data2 %>
  </div>
  <div class="field">
    <%= f.label :data3 %><br />
    <%= f.text_field :data3 %>
  </div>
  <div class="field">
    <%= f.label :data4 %><br />
    <%= f.text_field :data4 %>
  </div>
  <div class="field">
    
    Select Table
    <%= f.select :table_id, Table.find(:all).collect {|s|
[(s.name), s.id]} %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing column</h1>

<%= render 'form' %>

<%= link_to 'Show', @column %> |
<%= link_to 'Back', columns_path %>

app/views/columns/index.html.erb
<h1>Listing columns</h1>

<table>
  <tr>
    <th>Data1</th>
    <th>Data2</th>
    <th>Data3</th>
    <th>Data4</th>
    <th>Table</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @columns.each do |column| %>
  <tr>
    <td><%= column.data1 %></td>
    <td><%= column.data2 %></td>
    <td><%= column.data3 %></td>
    <td><%= column.data4 %></td>
    <td><%= column.table_id %></td>
    <td><%= link_to 'Show', column %></td>
    <td><%= link_to 'Edit', edit_column_path(column) %></td>
    <td><%= link_to 'Insert Values',column_rows_path(column) %></td>
    <td><%= link_to 'Destroy', column, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Column', new_column_path %>

app/views/columns/new.html.erb
<h1>New column</h1>

<%= render 'form' %>

<%= link_to 'Back', columns_path %>

app/views/columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data1:</b>
  <%= @column.data1 %>
</p>

<p>
  <b>Data2:</b>
  <%= @column.data2 %>
</p>

<p>
  <b>Data3:</b>
  <%= @column.data3 %>
</p>

<p>
  <b>Data4:</b>
  <%= @column.data4 %>
</p>

<p>
  <b>Table:</b>
  <%= @column.table_id %>
</p>
<h3>Values In columns</h3>
<table>
<tr>
<th>Data1</th>
<th>Data2</th>
<th>Data3</th>
<th>Data4</th>

</tr>
<%for t in @column.rows%>
<tr>
<td><%=t.value1%></td>
<td><%=t.value2%></td>
<td><%= t.value3%></td>
<td><%= t.value4 %></td>
<%end%> 


<%= link_to 'Edit', edit_column_path(@column) %> |
<%= link_to 'Insert values',column_rows_path(@column) %>|
<%= link_to 'Back', columns_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crypsis</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rows/_form.html.erb
<%= form_for([@column,@row]) do |f| %>
  <% if @row.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@row.errors.count, "error") %> prohibited this row from being saved:</h2>

      <ul>
      <% @row.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value1 %><br />
    <%= f.text_field :value1 %>
  </div>
  <div class="field">
    <%= f.label :value2 %><br />
    <%= f.text_field :value2 %>
  </div>
  <div class="field">
    <%= f.label :value3 %><br />
    <%= f.text_field :value3 %>
  </div>
  <div class="field">
    <%= f.label :value4 %><br />
    <%= f.text_field :value4 %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rows/edit.html.erb
<h1>Editing row</h1>

<%= render 'form' %>

<%= link_to 'Show', [@column,@row] %> |
<%= link_to 'Back', column_rows_path(@column) %>

app/views/rows/index.html.erb
<h1>Values stored for Table in given Rows</h1>
<% if !@column.rows.empty? %>

 <table>
   <tr>
     <th>Value1</th>
     <th>Value2</th>
     <th>Value3</th>
     <th>Value4</th>
     <th>Column</th>
     <th></th>
     <th></th>
     <th></th>
   </tr>

 <% @rows.each do |row| %>
   <tr>
     <td><%= row.value1 %></td>
     <td><%= row.value2 %></td>
     <td><%= row.value3 %></td>
     <td><%= row.value4 %></td>
     <td><%= row.column_id %></td>
     <td><%= link_to 'Show', [@column,row] %></td>
     <td><%= link_to 'Edit', edit_column_row_path(@column,row) %></td>
     <td><%= link_to 'Destroy', [@column,row], method: :delete, data: { confirm: 'Are you sure?' } %></td>
   </tr>
 <% end %>
<%else%>
 <p>Table empty</p>
<%end%> 
</table>

<br />

<%= link_to 'Add value', new_column_row_path(@column)%>
<%= link_to 'Back', @column %>

app/views/rows/new.html.erb
<h1>New row</h1>

<%= render 'form' %>

<%= link_to 'Back', column_rows_path %>

app/views/rows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value1:</b>
  <%= @row.value1 %>
</p>

<p>
  <b>Value2:</b>
  <%= @row.value2 %>
</p>

<p>
  <b>Value3:</b>
  <%= @row.value3 %>
</p>

<p>
  <b>Value4:</b>
  <%= @row.value4 %>
</p>

<p>
  <b>Column:</b>
  <%= @row.column_id %>
</p>


<%= link_to 'Edit', edit_column_row_path(@column,@row) %> |
<%= link_to 'Back', column_rows_path(@column) %>

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">

    Select Parent
    <%= f.select :parent_id,Table.find(:all ).collect {|s|
[(s.name), s.id]},{:include_blank => true, :default => nil} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tables.each do |table| %>
  <tr>
    <td><%= table.name %></td>
    <td><%= table.description %></td>
    <td><%= table.parent_id %></td>
    <td><%= link_to 'Show', table %></td>
    <td><%= link_to 'Edit', edit_table_path(table) %></td>
    <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @table.name %>
</p>

<p>
  <b>Description:</b>
  <%= @table.description %>
</p>

<p>
  <b>Parent:</b>
  <%= @table.parent_id %>
</p>


<p> table have following childtables</p>
<%if !@par.nil? %>
 <% @par.each do |a|%>
  Name: <%= a.name%></br>
 <%end%>
<%end%> 
</br>	
<% if !@col.nil? %>
schema name is table is<br/>
 

  <%= @col.data1 %> &nbsp
  <%= @col.data2 %> &nbsp
  <%= @col.data3 %> &nbsp
  <%= @col.data4 %> &nbsp
 
<%end%>  
</br>
<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>
<%if @col.nil? %>
 <%= link_to 'Add Schema', new_column_path %>
<%end%>